<?php
/**
 *  Printenbind additional model
 */
namespace Budbee\Model;

use \JsonSerializable;

/**
 * @author Erik Schoel
 */
class Parcel implements JsonSerializable
{
    public static $dataTypes = array(
        'id' => 'string',
        'shipmentId' => 'string',
        'packageId' => 'string',
        'label' => 'string'
    );

    /**
     * The ID of the end users purchase
     * @var string
     */
    public $id;

    /**
     * The shipment ID of the end users purchase
     * @var string
     */
    public $shipmentId;

    /**
     * The package ID of the end users purchase
     * @var string
     */
    public $packageId;

    /**
     * The label of the package generated by Budbee
     * @var string
     */
    public $label;

    public function jsonSerialize()
    {
        return array(
            'id' => $this->id,
            'shipmentId' => $this->shipmentId,
            'packageId' => $this->packageId,
            'label' => $this->label
        );
    }
}
